name: Deploy Frontend
on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
    - name: Build
      run: |
        cd frontend
        npm run build
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dreamai-frontend'
        publish-profile: ${{ secrets.FRONTEND_PUBLISH_PROFILE }}
        package: './frontend'
